rsa:
  public-key: classpath:certificates/public.pem
  private-key: classpath:certificates/private.pem
spring:
  datasource:
    username: ${PSQL_USERNAME}
    url: jdbc:postgresql://localhost:5432/fitness_app
    password: ${PSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: validate
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
server:
  error:
    include-message: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html
exercises:
  api-path: https://api.api-ninjas.com/v1/exercises
  api-key: 6CfUdEan1AkDYMoYPfybRA==jlm4cnVWW8emXOjk
